# Generated by Django 6.0.4 on 2026-05-02 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('project_number', models.CharField(blank=True, max_length=120)),
                ('file_reference', models.CharField(blank=True, max_length=120)),
                ('legal_basis', models.CharField(blank=True, max_length=80)),
                ('energy_basis', models.CharField(blank=True, max_length=80)),
                ('building_kind', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('calculation', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=255)),
                ('usage_profile', models.CharField(max_length=80)),
                ('area', models.FloatField(default=0)),
                ('setpoint_temperature', models.FloatField(default=0)),
                ('air_change_rate', models.FloatField(default=0)),
                ('internal_gains_density', models.FloatField(default=0)),
                ('occupancy_hours', models.FloatField(default=0)),
                ('gain_utilization_factor', models.FloatField(default=0)),
                ('payload', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='dashboard.project')),
            ],
        ),
    ]
