# Generated by Django 6.0.4 on 2026-05-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EkobaudatMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('producer', models.CharField(blank=True, max_length=250)),
                ('category', models.CharField(blank=True, max_length=250)),
                ('u_value', models.FloatField(blank=True, null=True)),
                ('embodied_co2', models.FloatField(blank=True, help_text='kg CO₂e pro m³ oder m²', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
